### ISSUE TITLE
oprava - Rosomák 2022

### ISSUE THREAD

**Issue by matyaskopp** [matyaskopp/zpevnik#4]
https://github.com/matyaskopp/zpevnik/pull/3#issue-1310062045

> Jarda se pustil do revize zpěvníčku. Co jsem uměl, jsem zapracoval. Řeší ale i ty mezery a rozdělovníky, které se tam přidávají kvůli akordům a s tím si neporadím... Podíval by ses na to prosím? Detail (výtah z Jardova mailu):
> - č.119 - "uvěříš" a "nalézám" by mohly být stejně psané... a asi bez rozdělovníků nebo odsazení slabik - jako všude jinde... ty akordy se nad slabiky plus mínus vejdou...
> - č.113 - 1. sloka: "staletí" - asi bych zrušil odsazení jednotlivých slabik... stejně jako v č.119 (i jinde)... chápu, že je to kvůli akordům, ale vypadá to divně. Otázka, jak to sjednotit. Podle mě buď všude nechat normální slova (což preferuji... akordy si hráč přizpůsobí a zpěvák melodii pochopí...), nebo všude rozdělovníky. Ty by pak ale, důsledně vzato, měly být i na ostatních analogických místech... U nás je rozdíl proti zápisu s notovou osnovou, tam jsou rozdělovníky nutné z principu...
> - č.112 - "pokoje" dohromady - bez oddělení slabiky

**Comment by matyaskopp** [comment]
@m-krystof opraveno.
aktuální verze je zde: https://matyaskopp.github.io/zpevnik/

**Comment by m-krystof** [comment]
Skvělý, díky!
