### ISSUE TITLE
Tohle b se nezobrazuje dobře... 

### ISSUE THREAD

**Issue by m-krystof** [matyaskopp/zpevnik#8]
https://github.com/matyaskopp/zpevnik/blob/6944e42f3d54196d73a168760d0c555c08adfe90/songs/diky.tex#L20
![image](https://github.com/matyaskopp/zpevnik/assets/87754763/94fb2589-a9e0-48a6-b4da-a798ed83e542)
Uměl bys ho přesvědčit, aby zůstalo písmenem?

**Comment by matyaskopp** [comment]
opraveno, přepsal jsem defaultní chování balíčku songbook
